% \VignetteIndexEntry{Using Data Packages}
% \VignetteDepends{hgu95av2, rae230a, rae230aprobe, Biostrings}
% \VignetteKeywords{Annotation}
%\VignettePackage{annotate}

\documentclass{article}

\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Rmethod}[1]{{\texttt{#1}}}

\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textit{#1}}}
\newcommand{\Rclass}[1]{{\textit{#1}}}

\usepackage{hyperref}

\usepackage[authoryear,round]{natbib}
\usepackage{times}

\begin{document}
\title{Using Probe Information}

\author{Robert Gentleman}
\date{}
\maketitle

\section*{Overview}

The Bioconductor project maintains a rich body of annotation data
assembled into R libraries. For many different Affymetrix chips
information is provided on both the sequence of the mRNA that was
intended to be matched and the actual 25mers that were used for the
bindings. In this vignette we show how to make use of the probe
information.

\section*{A Simple Example}

To demonstrate the use of probe level data we will use the
\texttt{rae230a} chip (for rats). So we first need to load these
libraries.

<<loadlibs>>=
library(rae230a)
library(rae230aprobe)
@

Now, we do not have any data so all we are going to do is to examine
the probe data and show how to use some of the different Bioconductor
tools to access that information, and potentially check on the mapping
information that has been given.

We will select a probe set,
<<selprobe>>=

ps = ls(env=rae230aACCNUM)

myp = ps[1001]

myA = get(myp, rae230aACCNUM)

wp = rae230aprobe$Probe.Set.Name == myp
myPr = rae230aprobe[wp,]

@

The probe data is stored as a \Rclass{data.frame} with 6 columns. They
are
\begin{description}
\item[sequence] The sequence of the 25mer
\item[x] The x position of the probe on the array.
\item[y] The y position of the probe on the array.
\item[Probe.Set.Name] The Affymetrix ID for the probe set.
\item[Probe.Interrogation.Position] The location (in bases) of the
13th base in the 25mer, in the target sequence.
\item[Target.Strandedness] Whether the 25mer is a Sense or an
Antisense match to the target sequence.
\end{description}

We note that it is not always the case that the sequence reported is
found in the reference or if it is, it is not always at the location
reported. One can check that using other tools available in the
\Rpackage{annotate} package and in the \Rpackage{Biostrings} package.

%%FIXME: need to check for connectivity
<<getACC>>=

myseq = getSeq4Acc(myA)
nchar(myseq)

library(Biostrings)
mybs = NucleotideString(myseq, "DNA")

match1 = matchDNAPattern(as.character(myPr[1,1]), mybs)
as.matrix(match1)
myPr[1,5]
@
And we can see that in this case the 13th nucleotide is indeed in
exactly the place that has been predicted. It is relatively
straightforward to check the other 25mers, and to develop different
visualization tools that can be used to investigate the available data.

\end{document}







